name: Deploy to Azure

on:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "pubspec.lock"
    branches:
      - master

env:
  STORAGE_ACCOUNT: jamslidepuzzle

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: deploy

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build Web'
      uses: actions/checkout@v2
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.2'
      run: |
        flutter pub get
        flutter build web
    
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT }}  --auth-mode key -d '$web' -s ./build/web
    
    # Azure logout
    - name: Azure logout
      run: |
        az logout
      if: always()
